<?php

/**
 * @var \Madar\StockAvailability\Block\Adminhtml\Order\View\DeliveryInfo $block
 * @var \Magento\Sales\Model\Order $order
 * @var \Magento\Sales\Model\Order\Address|null $shippingAddress
 */
$order = $block->getOrder();
$shippingAddress = $order ? $order->getShippingAddress() : null;
$latitude = $shippingAddress ? $shippingAddress->getData('latitude') : null;
$longitude = $shippingAddress ? $shippingAddress->getData('longitude') : null;

// Get source information
$sourceCode = $block->getAssignedSourceCode();
$branchPhone = $block->getDeliveryBranchPhone();
?>

<?php if (($latitude && $longitude) || $sourceCode): ?>
    <?php if ($sourceCode): ?>
        <tr>
            <th><?= $block->escapeHtml(__('Source Code')) ?></th>
            <td><?= $block->escapeHtml($sourceCode) ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Source Contact')) ?></th>
            <td><?= $block->escapeHtml($branchPhone) ?></td>
        </tr>
    <?php endif; ?>
    <?php if ($latitude && $longitude): ?>
        <tr>
            <th><?= $block->escapeHtml(__('Customer Delivery Location')) ?></th>
            <td><a href="<?= $block->escapeUrl($block->getGoogleMapsUrl($latitude, $longitude)) ?>"
                    target="_blank">
                    <?= $block->escapeHtml(__('View Source on Google Maps')) ?>
                </a></td>
        </tr>
    <?php endif; ?>
<?php endif; ?>